ktor:
    development: true
    deployment:
        port: 8000
        watch:
            - classes
            - resources
    application:
        modules:
            - com.example.ApplicationKt.module